server:
  port: 8081
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cjx913/microservice.git
          default-label: master
          search-paths:
            - /microservice-config-server/src/main/resources/config/
#          username:
#          password:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
