server:
  port: 8081
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri:
          default-label: master
          search-paths:
#          username:
#          password:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
